f=open('main.py','r',encoding='utf-8') 
c=f.read() 
f.close() 
c=c.replace('from output.formatter import format_findings','') 
c=c.replace('from output.reporter import print_summary','') 
c=c.replace('format_findings(findings, verbose=verbose, autofix=autofix)','') 
c=c.replace('print_summary(stats)','') 
c=c.replace('print_summary(1, stats.get(\"findings\",[]))','') 
f=open('main.py','w',encoding='utf-8') 
f.write(c) 
f.close() 
print('Done!') 
